"""Builder for launchpad/docs/corpus/specifications/normative-documents.md --
issue #1305.

Interpreting "normative" -- resolving a real ambiguity, not guessing past it
============================================================================

`templates/specification.md`'s own scope paragraph defines what a
`specification`-shaped node documents as "the complete normative definition of
one protocol, algorithm, or wire/data format." Read naively, that makes EVERY
node under `specifications/` normative by definition -- which would make this
document identical to #1302's `specifications/INDEX.md` (every canonical node
whose path starts with `specifications/`, full stop). That would be a pure
duplicate, and this builder deliberately does not take that reading.

Instead this builder treats "normative" the way `templates/specification.md`'s
own evidence ledger treated it when it went looking for a real, checkable
signal: it did not ask "is this document specification-typed" (a document's
own `type` deliberately varies by subject and proves nothing about whether it
declares a normative-language convention). It asked whether the document
**cites a normative-language convention by name** -- RFC 2119, RFC 8174, or
BCP 14 -- and it answered that question with a direct grep across
`docs/nips/*.md`: 7 of 16 files cite RFC 2119 alone, 9 cite nothing, and zero
cite the current RFC 8174-amended BCP 14 boilerplate. That is the same
methodology this builder applies here, to actual corpus nodes under
`specifications/` rather than to `docs/nips/*.md` prose.

The three-part inclusion rule (path, then type, then content) below is that
methodology made checkable and deterministic:

(a) `ctx.rel_path(n)` starts with the literal prefix `specifications/` -- the
    same base set #1302's builder walks. Membership starts from the same
    prefix `specifications_index.py` uses, never a separate directory guess.

(b) the node's own front-matter `type` is not `governance`. This corpus's own
    convention (confirmed by reading `specifications/INDEX.md`,
    `standards/generated-content.md`, `templates/generated-index.md`,
    `templates/specification.md`, and `README.md` -- every meta/index/policy
    document in the corpus) is that `governance` marks a document ABOUT the
    corpus or about how to write something, never a specification's own
    normative content. `templates/specification.md` itself says a real
    specification node's `type` varies by subject (`interfaces-events`,
    `architecture`, or `implementation`) -- never `governance`. This rule
    excludes exactly the one file `specifications/` currently contains,
    `INDEX.md` (`type: governance`, generated by #1302), which would
    otherwise be a false positive under rule (c): its own empty-listing
    message quotes `templates/specification.md`'s requirement for "a BCP 14
    normative-language" declaration, so a naive text search alone would
    wrongly count an index that MENTIONS the convention as a document that
    DECLARES it.

(c) the node's raw file text (front matter and body both -- a declaration may
    sit in either, per the batch dispatch brief's own "front-matter or body"
    framing) matches, case-insensitively, one of: `RFC 2119`, `RFC2119`,
    `RFC 8174`, `RFC8174`, `BCP 14`, `BCP14`. This is the identical keyword set
    `templates/specification.md`'s own evidence ledger greped `docs/nips/*.md`
    for -- reused here verbatim, not reinvented, so this builder's answer to
    "does this declare a normative-language convention" is the same question
    already asked and answered once in this batch, applied to a different
    corpus.

At the time this builder was written, `launchpad/docs/corpus/specifications/`
contains exactly one on-disk file besides this builder's own output,
`INDEX.md` -- but `indexes.py`'s own framework excludes every registered
builder's `output_path` from canonical inputs before any builder's
`generate(ctx)` ever runs (`build_context` filters `ctx.nodes`/`ctx.valid_nodes`
against the full discovered registry, not just the selected builder), so
`INDEX.md` (registered by `specifications-index`, #1302) and this builder's own
output are both already gone from `ctx.valid_nodes` by the time rules (a)-(c)
run at all. Verified directly: walking `validate.load_nodes` before applying
that exclusion still finds `specifications/INDEX.md`; walking `ctx.valid_nodes`
(after it) finds nothing under the prefix. So today's zero-candidate count is
the framework's own generated-output exclusion doing its job, not this
builder's rule (b) -- rule (b) would independently exclude `INDEX.md` on its
`type: governance` alone if it were ever a candidate (for example if a future
builder registry stopped registering it), but it has not yet had anything to
act on. The listing is honestly empty today; nothing here widens the rule to
manufacture a match.

What this document adds over #1302's `specifications-index.md`
================================================================

#1302's `specifications/INDEX.md` already lists every canonical node under the
`specifications/` prefix, regardless of type or content -- it is the complete
membership index of that subtree. This document is not a second copy of that
index. It answers a narrower, different question: of the nodes #1302 already
lists, which ones are both specification-shaped (excluding meta/index content
via rule (b)) AND make a checkable claim, in their own text, about which
normative-language convention their MUST/SHOULD/MAY usage follows (rule (c))?
A reader wanting "what specification content exists under `specifications/`"
reads #1302's `INDEX.md`. A reader wanting "which of those documents have
actually declared, checkably, that they follow BCP 14 (RFC 2119 + RFC 8174)"
reads this document instead. The generated body's own "Interpreting normative"
section (below, in `_generate`) restates this distinction for a reader who
opens only one of the two files.
"""

import re

_SPECIFICATIONS_PATH_PREFIX = "specifications/"
_EXCLUDED_META_TYPE = "governance"
_NORMATIVE_KEYWORD_RE = re.compile(
    r"RFC\s?2119|RFC\s?8174|BCP\s?14", re.IGNORECASE
)


def _declares_normative_convention(node) -> bool:
    """True iff the node's own raw file text (front matter or body) names
    RFC 2119, RFC 8174, or BCP 14 -- the same keyword set
    templates/specification.md's evidence ledger greped docs/nips/*.md for."""
    try:
        text = node.path.read_text(encoding="utf-8")
    except OSError:
        return False
    return bool(_NORMATIVE_KEYWORD_RE.search(text))


def _is_candidate_path(ctx, node) -> bool:
    return ctx.rel_path(node).startswith(_SPECIFICATIONS_PATH_PREFIX)


def _is_specification_shaped(node) -> bool:
    return node.data.get("type") != _EXCLUDED_META_TYPE


def _members(ctx):
    return sorted(
        (
            n
            for n in ctx.valid_nodes
            if _is_candidate_path(ctx, n)
            and _is_specification_shaped(n)
            and _declares_normative_convention(n)
        ),
        key=lambda n: ctx.rel_path(n),
    )


_INTERPRETING_NORMATIVE = """\
## Interpreting "normative"

`templates/specification.md`'s own scope paragraph calls a specification node
"the complete normative definition of one protocol" -- read on its own, that
would make every node under `specifications/` normative by definition, which
would make this document a duplicate of #1302's `specifications/INDEX.md`
(every canonical node under that prefix, regardless of type or content).

**This document does not use that reading.** It narrows "normative" to
"declares a normative-language (RFC 2119 / RFC 8174 / BCP 14) convention" --
a checkable content claim, not a type label -- following the exact methodology
`templates/specification.md`'s own evidence ledger already used when it greped
`docs/nips/*.md` for the same keyword set and found 7 of 16 files citing RFC
2119 alone, 9 citing nothing, and none citing the current RFC 8174-amended BCP
14 boilerplate.

**What #1302's `specifications/INDEX.md` already covers**: every canonical
corpus node whose path lives under `specifications/`, regardless of type or
content -- the complete membership index of that subtree.

**What this document adds**: the narrower subset of that same membership which
is both specification-shaped (excludes `governance`-typed meta/index content,
such as `INDEX.md` itself) and which makes a checkable claim, in its own file
text, about which normative-language convention its MUST/SHOULD/MAY usage
follows. A reader wanting the full subtree listing reads #1302's `INDEX.md`; a
reader wanting only the documents that have actually declared a
normative-language convention reads this document instead.
"""


def _generate(ctx):
    members = _members(ctx)

    lines = [_INTERPRETING_NORMATIVE, "## Documents declaring a normative-language convention", ""]
    if members:
        lines += ["| Id | Path | Status | Audiences |", "|---|---|---|---|"]
        for node in members:
            audiences = ", ".join(node.data.get("audiences") or [])
            lines.append(
                f"| `{node.id}` | `{ctx.rel_path(node)}` | "
                f"{node.data.get('status', '')} | {audiences} |"
            )
    else:
        lines += [
            "No canonical corpus node currently qualifies. At the time of",
            "writing, no node reaches rules (b) or (c) at all: the only",
            "on-disk file under `specifications/` besides this document's own",
            "output is `INDEX.md` (#1302's `specifications-index` builder),",
            "and the generator framework itself already excludes every",
            "registered builder's output path from canonical inputs before",
            "any builder's inclusion rule runs -- so `INDEX.md` is gone from",
            "the candidate set before this builder's own `type: governance`",
            "exclusion (rule b) or normative-keyword check (rule c) ever",
            "sees it. This is an honest empty listing, not an omission. It",
            "populates automatically once a real, non-`governance`-typed",
            "specification node is authored under that prefix and declares",
            "its own normative-language convention, per",
            "`launchpad/docs/corpus/templates/specification.md`",
            "(`corpus-template-specification`) required section 4.",
        ]

    return {
        "sections": "\n".join(lines),
        "includes": [
            "every canonical corpus node whose corpus-root-relative path "
            "begins with the literal prefix `specifications/` (the same base "
            "set #1302's specifications-index builder walks), AND whose "
            "front-matter `type` is not `governance` (excludes meta/index "
            "content living in that path, e.g. `specifications/INDEX.md` "
            "itself), AND whose raw file text (front matter or body) "
            "case-insensitively contains one of `RFC 2119`, `RFC2119`, "
            "`RFC 8174`, `RFC8174`, `BCP 14`, `BCP14` -- the identical "
            "keyword set `templates/specification.md`'s own evidence ledger "
            "greped `docs/nips/*.md` for"
        ],
        "excludes": [
            "any node outside the `specifications/` path prefix, regardless "
            "of type or content",
            "`governance`-typed nodes under `specifications/` (meta/index "
            "content, e.g. `specifications/INDEX.md`), even when their text "
            "happens to mention RFC 2119, RFC 8174, or BCP 14 while "
            "discussing the convention rather than declaring it for "
            "themselves",
            "specification-shaped nodes under `specifications/` that use "
            "MUST/SHOULD/MAY without naming which normative-language "
            "convention they follow -- using the words is not the same as "
            "declaring the convention, per "
            "`templates/specification.md` required section 4",
        ],
        "ordering": (
            "listing rows sorted lexicographically by corpus-root-relative path"
        ),
        "not_covered": [
            "The full membership of the `specifications/` subtree regardless "
            "of type or content -- that is #1302's `specifications/INDEX.md`, "
            "not this document.",
            "Whether a listed document's normative body actually uses its "
            "declared convention correctly -- this listing only checks that "
            "a convention is named in the node's own text, not that its "
            "MUST/SHOULD/MAY usage is internally consistent with it.",
        ],
        "unverified": [
            "Whether this builder's three-part rule -- path prefix, "
            "non-`governance` type, then a case-insensitive RFC "
            "2119/8174/BCP 14 keyword match -- correctly discriminates a real "
            "specification node has not been observed against any real "
            "specification content, because none exists in this corpus yet "
            "outside this builder's own test fixtures. The rule's behavior on "
            "an actual specification body (rather than a fixture built to "
            "exercise it) is untested.",
        ],
    }


def _extra_evidence(ctx):
    candidates = [n for n in ctx.valid_nodes if _is_candidate_path(ctx, n)]
    excluded_by_type = [n for n in candidates if not _is_specification_shaped(n)]
    members = _members(ctx)
    return [
        {
            "statement": (
                f"At input digest sha256:{ctx.input_digest}, exactly "
                f"{len(candidates)} canonical node(s) in `ctx.valid_nodes` have a "
                "corpus-root-relative path beginning `specifications/`; of those, "
                f"{len(excluded_by_type)} carry front-matter `type: governance` "
                "and are excluded by this builder's rule (b); of the remainder, "
                f"exactly {len(members)} case-insensitively name RFC 2119, "
                "RFC 8174, or BCP 14 in their own file text and are listed here. "
                "The candidate count is 0 today not because rule (b) or (c) "
                "excluded anything, but because `indexes.py`'s own framework "
                "excludes every registered builder's output path -- including "
                "`specifications/INDEX.md` (#1302) and this builder's own output "
                "-- from `ctx.valid_nodes` before any builder's generate(ctx) "
                "runs; walking `validate.load_nodes` directly (before that "
                "exclusion) still finds `specifications/INDEX.md` on disk."
            ),
            "entry_class": "FACT",
            "evidence": ["launchpad/project-intelligence/corpus/validate.py"],
        },
        {
            "statement": (
                "templates/specification.md's own evidence ledger reports that "
                "of Buzz's 16 docs/nips/*.md files, 7 (NIP-AA, NIP-CW, NIP-DV, "
                "NIP-IA, NIP-MP, NIP-PL, NIP-WP) cite RFC 2119 alone, 9 "
                "(including NIP-AM.md) declare no normative-language convention "
                "at all, and zero cite RFC 8174 or 'BCP 14' by name -- the same "
                "keyword set and methodology this builder's rule (c) reuses, "
                "applied to actual specifications/ corpus nodes rather than to "
                "docs/nips/*.md prose."
            ),
            "entry_class": "FACT",
            "evidence": [
                "launchpad/docs/corpus/templates/specification.md",
            ],
        },
    ]


SPEC = {
    "name": "normative-documents",
    "output_path": "specifications/normative-documents.md",
    "node_id": "specifications-normative-documents",
    "title": (
        "Normative documents index: specifications declaring a "
        "normative-language convention"
    ),
    "node_type": "governance",
    "audiences": ("agent", "developer", "reviewer"),
    "subject": (
        "canonical corpus nodes under the specifications/ prefix that "
        "declare a normative-language (RFC 2119 / RFC 8174 / BCP 14) "
        "convention in their own text"
    ),
    "generate": _generate,
    "extra_evidence": _extra_evidence,
    "relationships": (
        {"type": "references", "target": "corpus-agents"},
        {"type": "implements", "target": "corpus-template-generated-index"},
        {"type": "references", "target": "corpus-template-specification"},
    ),
}
