"""Fail-closed bundle assembly and nonce envelopes — `code/P-06-harness-interface.md` §5.

This module is the reason P-06 exists as a separate part. It is the one place in RQA
where pull-request bytes are written somewhere a model will read them, so §5's rule is
enforced here as a structural invariant rather than as a checklist of fields:

> **Every artifact file in a bundle is exactly one envelope.**

Not "every PR-derived field is enveloped" — *every artifact*, PR-derived or not. Two
things follow, and both are the point. First, §5's "no PR-derived byte is emitted
outside an envelope" becomes decidable by walking the produced tree rather than by
trusting an enumeration of fields: strip every `<<<label:nonce>>>…<<<END:label:nonce>>>`
block keyed on this bundle's nonce and the residue must contain no pull-request byte at
all. An enumeration is exactly what an attacker gets to be absent from. Second, §5's
"the manifest contains only bundle-generated nonce, snapshot protocol hash, and hashes
of already-enveloped artifacts" is literally true, because there is no other kind of
artifact to hash.

**Artifact names are bundle-generated, never PR-derived.** A changed-path name used as
a filename inside the bundle is a PR byte outside an envelope — the filename is not in
the file. So every captured file gets an ordinal name (`artifacts/files/000001`) and the
path it came from lives, enveloped, inside `artifacts/file_index`. The same reasoning
retires check names, label text and branch names from every structural position.

**Binary is base64, and losslessly so.** `Facts.files` is `Mapping[str, bytes]`; those
bytes are not text and `envelope()` is a string grammar. §5: "arbitrary file bytes are
losslessly base64 encoded and that representation is envelope-encoded". `extract()` then
`b64decode` returns the original bytes for any input, including bytes that are not valid
UTF-8 and bytes that contain the envelope markers themselves.

**The envelope grammar is imported, never reimplemented.** `rqa.protocol.envelope` and
`rqa.protocol.fence` are P-04's, landed, and hardened over three gate rounds. A second
implementation of either in this package would be a second grammar, which is how a
nonce envelope stops being one thing the receiver can identify (U-RESILIENCE-15, kept;
U-DOCS-26, salvaged: the mechanism is matching per-invocation open/close delimiters,
re-targeted from a test onto this writer).

**Fail-closed publication.** The bundle is staged in a sibling directory, every file and
the manifest are flushed and `fsync`-ed, the staging directory itself is `fsync`-ed, and
only then is it `os.rename`-d into place. A failed assembly removes the staging tree and
leaves no final bundle directory, so a partially-written bundle can never be invoked
against. That is U-VERDICT-07's fail-closed collection, kept: "a model handed a short
bundle reviews it rather than refusing it, so the shortfall surfaces as a confident
verdict rather than an error."

`BundleFailure.reason` is built from the failing artifact's *bundle-relative* name and
the exception's type — never from PR content, never from a filesystem message that could
quote one. The `raise ... from None` discipline `errors.py` describes applies here too:
nothing in this module lets untrusted bytes reach a traceback chain.
"""

from __future__ import annotations

import base64
import hashlib
import json
import os
import shutil
from collections.abc import Mapping, Sequence
from dataclasses import dataclass
from pathlib import Path
from secrets import token_hex
from typing import TYPE_CHECKING

from rqa.contracts import BundleFailure
from rqa.harness.errors import ProtocolVersionUnknown
from rqa.protocol import PROTOCOL_VERSION, envelope, protocol_hash
from rqa.protocol.version import schema_path

if TYPE_CHECKING:  # annotation-only; resolved by type checkers, never at import
    from rqa.contracts import Facts, Snapshot

__all__ = [
    "BUNDLE_DIRNAME",
    "Bundle",
    "MANIFEST_NAME",
    "NONCE_BYTES",
    "assemble",
    "assemble_into",
    "protocol_instruction_path",
    "text_artifacts",
]

#: The published directory name, under `state_dir/jobs/<job>/` (§5).
BUNDLE_DIRNAME = "bundle"
#: The manifest's fixed name inside a bundle.
MANIFEST_NAME = "manifest.json"
#: Subdirectory holding every envelope. Keeping them under one name means the manifest's
#: artifact keys and the on-disk layout cannot drift apart.
ARTIFACTS_DIRNAME = "artifacts"
#: Ordinal-named captured files live here; their real paths live enveloped in `file_index`.
FILES_DIRNAME = "files"
#: 16 bytes of `secrets` entropy, hex-encoded. A per-bundle nonce, generated by RQA:
#: content cannot forge a delimiter it has never seen (U-RESILIENCE-15).
NONCE_BYTES = 16


@dataclass(frozen=True)
class Bundle:
    """A published bundle: where it is, the nonce that keys it, and what it contains.

    Private to P-06 — it never crosses a part boundary, so `CONTRACTS.md` §1's rule that
    a part contract may add only types that stay inside the part is satisfied by
    construction. What crosses the boundary is `BundleFailure`, which is shared.
    """

    path: Path
    nonce: str
    protocol_hash: str
    manifest: Mapping[str, object]


def protocol_instruction_path() -> Path:
    """The immutable protocol instruction handed to every harness (§3.3).

    `PROTOCOL.md` as this build packages it, under version control beside the schema —
    never written into `state/`, never assembled from policy, and never derived from PR
    content. It is the *only* instruction in an invocation; everything else is data.
    """
    return schema_path().parent.parent / "PROTOCOL.md"


def _wrap(*, label: str, nonce: str, content: str) -> str:
    return envelope(label=label, nonce=nonce, content=content)


def _render_labels(labels: frozenset[str]) -> str:
    return "\n".join(sorted(labels))


def _render_checks(checks: Sequence[object]) -> str:
    lines = []
    for check in checks:
        # `CheckRun.conclusion` is an Enum member; `.value` is the canonical string.
        lines.append(f"{check.name}\t{check.conclusion.value}\t{check.sha}")  # type: ignore[attr-defined]
    return "\n".join(sorted(lines))


def _render_reviews(reviews: Sequence[object]) -> str:
    """The comment channel.

    `Facts` (P-09, landed) carries no comment bodies — `SubmittedReview` is id, actor,
    outcome, head sha and time. That is the whole of the pull-request conversation RQA
    holds, so it is what this artifact carries, and `InjectionAttempt.field`'s
    `comment:<id>` addresses a row of it. If P-09 later captures comment text, it joins
    this artifact; nothing else has to move.
    """
    lines = []
    for review in reviews:
        lines.append(
            f"comment:{review.id}\t{review.actor}\t{review.outcome}\t{review.head_sha}"  # type: ignore[attr-defined]
        )
    return "\n".join(sorted(lines))


def _render_identity(facts: Facts) -> str:
    pr = facts.pr
    return "\n".join(
        (
            f"repo\t{pr.repo}",
            f"number\t{pr.number}",
            f"head_sha\t{pr.head_sha}",
            f"base_sha\t{pr.base_sha}",
            f"merge_base_sha\t{pr.merge_base_sha}",
            f"head_repo\t{pr.head_repo}",
            f"head_ref\t{pr.head_ref}",
            f"author\t{pr.author}",
        )
    )


def _render_authority(snapshot: Snapshot) -> str:
    """RQA's own statement of the authority mode this review runs under.

    Not PR-derived, and enveloped anyway: one artifact shape means one rule to check.
    """
    return "\n".join(
        f"{activity.value}\t{'1' if allowed else '0'}"
        for activity, allowed in sorted(
            snapshot.authority.items(), key=lambda item: item[0].value
        )
    )


def text_artifacts(*, facts: Facts, snapshot: Snapshot) -> Mapping[str, str]:
    """Every text artifact's bundle-relative name and its pre-envelope content.

    Split out from `assemble` so a test can enumerate the channels without touching a
    filesystem, and so the enumeration has exactly one definition.
    """
    return {
        "pr_identity": _render_identity(facts),
        "title": facts.pr.title,
        "body": facts.pr.body,
        "labels": _render_labels(facts.pr.labels),
        "diff": facts.diff,
        "changed_paths": "\n".join(sorted(facts.changed_paths)),
        "comments": _render_reviews(facts.reviews),
        "checks": _render_checks(facts.checks),
        "base_checks": _render_checks(facts.base_checks),
        "authority": _render_authority(snapshot),
        "fetched_at": facts.fetched_at.isoformat(),
    }


def _write(path: Path, data: bytes) -> None:
    """Write and flush to the platter. `fsync` before the rename is what makes the
    published bundle durable rather than merely visible."""
    with open(path, "wb") as handle:
        handle.write(data)
        handle.flush()
        os.fsync(handle.fileno())


def _fsync_dir(path: Path) -> None:
    descriptor = os.open(path, os.O_RDONLY)
    try:
        os.fsync(descriptor)
    finally:
        os.close(descriptor)


def assemble(*, job_id: str, facts: Facts, snapshot: Snapshot, state_dir: Path) -> Bundle | BundleFailure:
    """The job's own bundle at `state_dir/jobs/<job>/bundle` (§5), or why it failed."""
    return assemble_into(parent=state_dir / "jobs" / job_id, facts=facts, snapshot=snapshot)


def assemble_into(*, parent: Path, facts: Facts, snapshot: Snapshot) -> Bundle | BundleFailure:
    """Assemble and atomically publish one bundle under `parent`, or return why it could not be.

    `parent` is the job directory for the review's own bundle and the harness slot for a
    §3.2 step 2 conformance bundle; both are inside the two trees §5 permits this part to
    write, and both get byte-identical treatment, which is what makes the conformance run
    a genuine rehearsal of the invocation it gates.

    Raises `ProtocolVersionUnknown` when `snapshot.protocol_hash` is not the protocol
    this build packages: that is a deployment defect, not a bundle that failed to write.
    """
    packaged = protocol_hash()
    if snapshot.protocol_hash != packaged:
        raise ProtocolVersionUnknown(
            f"snapshot pins protocol hash {snapshot.protocol_hash} but this build "
            f"packages version {PROTOCOL_VERSION} at {packaged}"
        )

    job_dir = parent
    final = job_dir / BUNDLE_DIRNAME
    nonce = token_hex(NONCE_BYTES)
    staging = job_dir / f".{BUNDLE_DIRNAME}.staging-{nonce}"
    artifact = "<setup>"
    try:
        if final.exists():
            # A bundle from an earlier run of this job. U-VERDICT-12's clearing rule
            # applied to the bundle: a re-run must not be able to invoke against bytes
            # captured under an earlier head.
            shutil.rmtree(final)
        shutil.rmtree(staging, ignore_errors=True)
        (staging / ARTIFACTS_DIRNAME / FILES_DIRNAME).mkdir(parents=True)

        hashes: dict[str, str] = {}

        def publish(name: str, content: str) -> None:
            wrapped = _wrap(label=name, nonce=nonce, content=content).encode("utf-8")
            _write(staging / ARTIFACTS_DIRNAME / name, wrapped)
            hashes[name] = hashlib.sha256(wrapped).hexdigest()

        for artifact, content in text_artifacts(facts=facts, snapshot=snapshot).items():
            publish(artifact, content)

        index_lines: list[str] = []
        for ordinal, path in enumerate(sorted(facts.files), start=1):
            name = f"{FILES_DIRNAME}/{ordinal:06d}"
            artifact = name
            wrapped = _wrap(
                label=name,
                nonce=nonce,
                content=base64.b64encode(facts.files[path]).decode("ascii"),
            ).encode("utf-8")
            _write(staging / ARTIFACTS_DIRNAME / name, wrapped)
            hashes[name] = hashlib.sha256(wrapped).hexdigest()
            index_lines.append(f"{name}\t{path}")
        artifact = "file_index"
        publish("file_index", "\n".join(index_lines))

        manifest: Mapping[str, object] = {
            "nonce": nonce,
            "protocol_hash": snapshot.protocol_hash,
            "artifacts": dict(sorted(hashes.items())),
        }
        artifact = MANIFEST_NAME
        _write(
            staging / MANIFEST_NAME,
            json.dumps(manifest, sort_keys=True, separators=(",", ":")).encode("utf-8"),
        )
        _fsync_dir(staging / ARTIFACTS_DIRNAME / FILES_DIRNAME)
        _fsync_dir(staging / ARTIFACTS_DIRNAME)
        _fsync_dir(staging)
        os.rename(staging, final)
        _fsync_dir(job_dir)
    except (OSError, ValueError, UnicodeError, TypeError, AttributeError) as exc:
        shutil.rmtree(staging, ignore_errors=True)
        shutil.rmtree(final, ignore_errors=True)
        # Type and artifact name only. Neither is PR-derived: artifact names are this
        # module's own. Returning a value rather than raising is also why no traceback
        # chain — which had the PR bytes in scope — can escape this frame at all.
        return BundleFailure(reason=f"{type(exc).__name__} writing {artifact}")

    return Bundle(path=final, nonce=nonce, protocol_hash=snapshot.protocol_hash, manifest=manifest)
